# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f022082a3c2f7a0187692f7605bac1aaa1f624cd34d4ca7c272fc0ba46dc40882a8f49c6bd059ea451b491ebaf497a02403f345b62b14f899c3ff007305f2a95

test:
  secret_key_base: 2b49ec99b64499281b53e1e96c91a2370cfbe760fa3172f396c33e4c1af5aa557cb67c23d6f2fbe5921dbdc2c819bb0dc3836a0f5c00ce15708dd4b90ecfc1f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
